### ISSUE TITLE
1월 판교 소모임 결과

### ISSUE THREAD

**Issue by seapy** [awskrug/meetups#1]
어떻게 정리해야될지 아직 잘 모르겠는데 우선 이슈로 남겨봅니다.

---
어제 열렸던 판교 소모임 발표 내용 및 사진이에요

- AWS Cognito Federation Identity의 사용법과 역할 - 박진언 
https://jinunpark.github.io/awskrug_20170106_introduction_to_aws_cognito

- 클라우드에서의 보안 - 정도현
http://www.slideshare.net/AmazonWebServices/intro-to-aws-security-50364629

- AWS re:invent 2016 후기 - 정창훈
http://www.slideshare.net/seapy/aws-reinvent-2016

![temp_1483704042584 -1352700393](https://cloud.githubusercontent.com/assets/421486/21739731/d92685ae-d4e6-11e6-931a-6fd6f58fbf59.jpeg)

**Comment by serithemage** [comment]
일단 제가 markdown으로 만들어서 pull request를 올리긴 했는데 사진도 첨부하는게 좋겠죠?

**Comment by seapy** [comment]
네 사진도 있으면 좋을거 같아요 ^^

**Comment by serithemage** [comment]
발표자료 이외에 모임에서 논의 되었던 내용들도 함께 올리면 좋을듯 합니다. 슬랙에서 가져와서 정리해 볼께요.
